# Generated by Django 2.2.10 on 2020-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Team Lead', 'Team Lead'), ('Senior', 'Senior'), ('Associate', 'Associate'), ('Consultant', 'Consultant')], max_length=1, null=True),
        ),
    ]
