# Generated by Django 2.2.10 on 2020-03-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200305_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('M', 'Manager'), ('E', 'Employee')], max_length=1, null=True),
        ),
    ]
