# Generated by Django 2.2.10 on 2020-03-03 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarinhoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='Employees',
            field=models.ManyToManyField(blank=True, related_name='Engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
