# Generated by Django 2.2.10 on 2020-03-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarinhoApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.DeleteModel(
            name='www',
        ),
    ]
