# Generated by Django 2.2.6 on 2020-02-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarinhoApp', '0002_auto_20200202_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='employee',
            new_name='emp',
        ),
    ]
