# Generated by Django 3.0.3 on 2020-03-16 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CalendarinhoApp', '0002_client_clicode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CliName',
            field=models.CharField(max_length=200, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='CliShort',
            field=models.CharField(max_length=10, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='CliName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CalendarinhoApp.Client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='EngName',
            field=models.CharField(help_text="Don't forget to use the naming convention we have in this URL <a href='#'>HERE</a>", max_length=200, verbose_name='Engagement Name'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='ServiceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CalendarinhoApp.Service', verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceName',
            field=models.CharField(max_length=200, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceShort',
            field=models.CharField(max_length=10, verbose_name='Service Shortname'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('eng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CalendarinhoApp.Engagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
