# Generated by Django 2.2.3 on 2020-11-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarinhoApp', '0003_auto_20200316_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['CliName']},
        ),
    ]
