# Generated by Django 2.2.6 on 2020-03-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarinhoApp', '0003_auto_20200224_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=200)),
                ('serviceShort', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='engagement',
            name='ServiceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CalendarinhoApp.Services'),
        ),
    ]
